# Generated by Django 3.0.5 on 2020-04-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='blog_id',
            new_name='blog',
        ),
        migrations.RemoveField(
            model_name='block',
            name='block_id',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blog_id',
        ),
        migrations.AddField(
            model_name='block',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
