# Generated by Django 3.0.5 on 2020-04-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='isMerged',
            field=models.BooleanField(default=False),
        ),
    ]
