# Generated by Django 3.0.5 on 2020-04-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_block_ismerged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='img',
        ),
        migrations.AddField(
            model_name='blog',
            name='isPublished',
            field=models.BooleanField(default=False),
        ),
    ]
