# Generated by Django 3.0.5 on 2020-04-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200409_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
