# Generated by Django 3.0.5 on 2020-05-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200508_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cover_img',
            field=models.ImageField(default='images/img3.svg', upload_to='blog_covers/'),
        ),
    ]
