# Generated by Django 3.0.5 on 2020-05-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200508_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/blocks/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='block',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='cover_img',
            field=models.ImageField(default='blog_covers/img5.jpg', upload_to='blog_covers/%y/%m/%d'),
        ),
    ]
